apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  namespace: bits-demo
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: hello-world
              servicePort: 80